version: '3.9'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
    depends_on:
      - api_add
      - api_subtract
  api_add:
    build:
      context: ./api_add
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - db
  api_subtract:
    build:
      context: ./api_subtract
      dockerfile: Dockerfile
    ports:
      - "5001:5000"
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example_password
      POSTGRES_DB: api_data
    volumes:
      - db_data:/var/lib/postgresql/data
volumes:
  db_data:
